# Generated by Django 3.2.4 on 2021-06-05 17:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('state', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('Urgent', 'Urgent')], default='Normal', max_length=20)),
            ],
        ),
    ]
