# Generated by Django 3.2.4 on 2021-06-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Family', 'Family'), ('Work', 'Work'), ('Study', 'Study'), ('Cars', 'Cars'), ('Friends', 'Friends'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
