# Generated by Django 3.2.4 on 2021-06-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_category_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='category',
        ),
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.ManyToManyField(to='todos.Category'),
        ),
        migrations.RemoveField(
            model_name='todo',
            name='priority',
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.ManyToManyField(to='todos.Priority'),
        ),
    ]
