# Generated by Django 3.2.4 on 2021-06-05 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20210605_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='category',
        ),
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todos.category'),
        ),
        migrations.RemoveField(
            model_name='todo',
            name='priority',
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todos.priority'),
        ),
    ]
