# Generated by Django 3.2.4 on 2021-06-07 11:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_auto_20210605_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 11, 26, 2, 621623, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 11, 26, 2, 621569, tzinfo=utc)),
        ),
    ]
