# Generated by Django 3.2.4 on 2021-06-03 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_todo_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='text',
            new_name='title',
        ),
    ]
