# Generated by Django 3.2.4 on 2021-06-10 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_auto_20210607_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='state',
            new_name='is_done',
        ),
    ]
