# Generated by Django 3.2.4 on 2021-06-04 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_alter_todo_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
